version: '3.9'
volumes:
  mysql:
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: a2d4a3178f9d17a616c487f2ba83fea8
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/data
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
  tradebox:
    image: albreis/tradebox:v2
    build: .
    ports:
      - 80:80
    command: >
      bash -c "a2enmod rewrite
      && apache2-foreground"
    volumes:
      - ./app:/var/www/html